/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct custom_string {
	struct {
		u_int str_len;
		char *str_val;
	} str;
};
typedef struct custom_string custom_string;

#define CAL_PROG 0x31111111
#define CAL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULATE 1
extern  int * calculate_1(custom_string *, CLIENT *);
extern  int * calculate_1_svc(custom_string *, struct svc_req *);
extern int cal_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULATE 1
extern  int * calculate_1();
extern  int * calculate_1_svc();
extern int cal_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_custom_string (XDR *, custom_string*);

#else /* K&R C */
extern bool_t xdr_custom_string ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
