/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"

bool_t
xdr_custom_string (XDR *xdrs, custom_string *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->str.str_val, (u_int *) &objp->str.str_len, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_custom_response (XDR *xdrs, custom_response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->is_valid))
		 return FALSE;
	return TRUE;
}
